#+TITLE:     Corgi User Manual
#+AUTHOR:    Arne Brasseur
#+EMAIL:     arne@lambdaisland.com
#+LANGUAGE:  en

* Principles

** Minimal

Minimal is relative, one person's essential is an other person's bloat. What do
we mean for Corgi to be minimal?

First off we limit the amount of packages that Corgi pulls in, even though some
of the packages we do pull in are fairly large. Beyond that we limit the amount
of customization we do beyond what these packages provide.

Combined this brings several benefits. It keeps Emacs running smoothly. It
limits the number of moving parts, so there is less that can go wrong. And it
makes it possible for people to keep an overview of what is it they are
installing.

** Reproducible installs

The modern Emacs ecosystem has gone far beyond what it is was originally
intended for. People are doing increasingly impressive and complex things on top
of this humble LISP runtime, with packages recursively depending on dozens if
not hundreds of other packages.

Sadly our practices have not kept up with this reality. Two people can install
the same Emacs config minutes apart, but still get different versions of
packages, so no one is actually running the same code as anyone else. You are
almost certainly getting a combination of package versions that was never tested
before. Predictably this leads to breakage.

This is partly technical and partly cultural, it seems the diligence to not
introduce breaking API changes is not pervasive yet, and frankly the language
and package system provide little affordances to limit the blast radius.

[[https://github.com/raxod502/straight.el][straight.el]] seeks to rectify this by providing reproducible installs. All
packages are installed via Git, using specific commit hashes, which are "frozen"
in a version file. When first using Corgi it will install its own version file,
so you get the exact same code that Corgi was developed and tested with.

** Packages all the way down

When installing Corgi we don't give you a huge ~.emacs.d~ directory to copy,
instead you create your own, and simply pull in the ~corgi~ package. Beyond that
it's a standard Emacs config, and it's *your config*. Add customizations to
~.emacs.d/init.el~ to your heart's content.

Corgi itself is a collection of packages like ~corgi-editor~, ~corgi-defaults~,
or ~corgi-emacs~, and most of what these do is pulling in and configuring other
packages. If you don't like what any of them is doing, then copy the relevant
package over to your personal config and customize it from there.

** Vim-style modal editing

There are two schools of thought for how to do editor key bindings, /modal/ and
/key-chord/. Emacs traditionally is a key-chord style editor, you combine keys
with one or more modifiers in elaborate "chords". The vi/vim family of editors
instead uses different editor "modes", like "normal mode", "insert mode", or
"visual mode". What each key does depends on the current mode, in insert mode
pressing `D` will insert the letter "D", but in normal mode it will delete up to
the end of the line. 

Not all commands can be bound to a single key like that, others are bound to key
sequences. `gg` goes to the beginning of the buffer. `,ep` evaluates and
expression and pretty prints the result.

(Note that Emacs has a separate, unrelated concept of
modes. To differentiate them these vim-style modes are also referred to as
states.)

There are two reasons why we have made a strong decision to promote the modal
style: RSI, and command composition.

RSI or /repetitive strain injury/, also known as a "mouse arm" or "emacs pinky"
is an inflammation of the neural pathways in the arm and wrist. It's a painful
affliction that many programmers suffer from, and recovering can be a long and
frustrating process, sometimes forcing people to put their programming career on
hold for extended periods of time.

The Emacs key chords can be a contributing factor to RSI. It is telling that a
common form of RSI among Emacs users shows up in the left pinky, used to press
Ctrl over and over. It seems in contrast that pressing single keys in sequence,
so the hands do less moving around and less stretching out, is easier on the
body.

This alone should be a fairly compelling argument, but modal editing isn't only
good for your health, it will also make you a more productive programmer. See,
these single keypress commands don't just exist in isolation, they can be
combined into "sentences" to very concisely express complex operations.

#+begin_src 
<number><command><text object or motion>
#+end_src

In normal mode `w` moves forward by one word. `3w` moves forward by 3 words.
`dw` deletes the next word. `3dw` deletes the next 3 words. Combining these
commands and text objects allows you to do in two or three key strokes what
might be a lot of bouncing the cursor around and pressing several key chords
otherwise.

Some more examples:

- `2yL` copy ("yank") the next 2 s-expressions
- `c$` "change" from cursor position to the end of the line, this deletes the
  relevant section and changes to insert mode
- `cs(]` change surrounding parenthesis to brackets
- `di"` delete inner string, i.e. delete everything inside the surrounding
  double quotes

** Keybindings all live in one place
** First class terminal and GUI support

* Installation
** Installing Emacs

/TODO: These instructions were written a few years ago, check if they are still accurate./

How to install Emacs depends on your operating system. Make sure you install
"GNU Emacs", and not an alternative version like "XEmacs" or "Aquamacs".

*** Windows

Windows versions of GNU Emacs are distributed as zip-files, which can be found
on [[http://ftpmirror.gnu.org/emacs/windows/][gnu.org ftp mirrors]]. Find the zip file with the highest version number, at
time of writing this is ~emacs-24.5-bin-i686-mingw32.zip~, and download it.

Create a directory where you want to put Emacs, for example ~C:\Program
Files\Emacs~ and unpack the zip file there.

The ~runemacs.exe~ program in the ~bin~ directory will start Emacs. The
~addpm.exe~ program will add Emacs to the start menu.

*** OS X

OS X already comes with a version of Emacs installed, but it's very old (Emacs
22), and it doesn't have GUI support, so it only works inside a terminal. You
want to avoid using this version.

If you have Homebrew available then that is the most straightforward option.

#+BEGIN_SRC sh
$ brew update
$ brew install emacs --with-cocoa
$ brew linkapps emacs
#+END_SRC

Alternatively you can download a ~.dmg~ at [[https://emacsformacosx.com/][emacsformacosx.com]].

That should be enough to get you going. Emacs Redux has some more tips on
[[http://emacsredux.com/blog/2015/05/09/emacs-on-os-x/][setting up Emacs on OS X]].

*** Linux

Your package manager should have ready-made packages available. If you have a
graphical package manager look for an "emacs" package, or install the package
from the command line with ~apt-get~ or ~yum~.

** Configuring Emacs: straight.el, use-package, corgi-packages

Corgi differs from other Emacs configurations like Spacemacs, Doom, or Prelude
in that it's not an Emacs configuration at all, instead it is a collection of
packages that are meant as a foundation for building your own config.

These packages are distributed via Git, and can be installed with the
straight.el functional package manager, so you will not find them on MELPA or
similar repositories. These Corgi packages take care of various bits of Emacs
boilerplate, as well as installing and configuring a set of base packages for
you, so you get a system that is pleasant to use out of the box. To configure
these third-party packages Corgi uses ~use-package~.

This means that a corgi-based Emacs config consists of four parts

- Install straight.el
- Install use-package
- Install corgi packages
- Do your own setup

Here's a basic config to get you started:

#+begin_src emacs-lisp
;; ~/.emacs or ~/.emacs.d/init.el

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Install straight.el

(defvar bootstrap-version)

(let ((install-url "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el")
      (bootstrap-file (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer (url-retrieve-synchronously install-url 'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
  
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Install and enable use-package

(straight-use-package 'use-package)

(setq straight-use-package-by-default t)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Install Corgi

(use-package corgi-packages
  :straight (corgi-packages
             :type git
             :host github
             :repo "lambdaisland/corgi-packages"))

(add-to-list #'straight-recipe-repositories 'corgi-packages)

(let ((straight-current-profile 'corgi))
  (use-package corgi-defaults)
  (use-package corgi-editor)
  (use-package corgi-emacs-lisp)
  (use-package corgi-commands)
  (use-package corgi-clojure)
  (use-package corgi-stateline)
  (use-package corkey
    :config
    (corkey-mode 1)
    (corkey/install-bindings)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Your own stuff goes here, we recommend these extra packages

(use-package markdown-mode)
(use-package yaml-mode)
(use-package org)
(use-package magit)
#+end_src

* Key bindings

Corgi's key system is provided by one of a Corgi package called
[Corkey](https://github.com/lambdaisland/corgi-packages/tree/main/corkey). It
contains the key binding functionality based on simple configuration files, as
well as Corgi's default bindings.

You can find all binding definitions in [[https://github.com/lambdaisland/corgi-packages/blob/main/corkey/corgi-keys.el][corgi-keys.el]] and [[https://github.com/lambdaisland/corgi-packages/blob/main/corkey/corgi-signals.el][corgi-signals.el]]. The
~keys~ file contains the actual bindings as a nested datastructure, bound to
symbolic ~signals~ (keywords). E.g.

#+begin_src emacs-lisp
  (("SPC" "Global leader key"
    ("f" "File commands"
     ("f" "Find file" :file/open))))
#+end_src

The ~signals~ file provides the mapping from this keyword to an actual Emacs
command, based on the current major mode or minor modes.

#+begin_src emacs-lisp
  ((corkey-local-mode (:file/open counsel-find-file)))
#+end_src

This indirection serves two purposes. It allows you to change the command you
want to use for a certain action like opening a file, indepently of its
keybinding. So you can configure the command you want to use, and have it work
consistently even when switching between different sets of bindings.

The other purpose is to provide mnemonic bindings that work in a mode-specific
way. E.g. ~SPC s s~ invokes the signal ~:repl/toggle~. In Clojure mode this will
be bound to ~cider-switch-to-repl-buffer~, whereas in Emacs LISP mode it will
call ~ielm~, and in SQL mode it does a ~sql-show-sqli-buffer~. Each brings you
to the REPL associated with the file you are working on.

If you decide you don't like ~SPC s s~ for this functionality then you can
rebind that, and it will work accordingly in all these modes.

** Keys to get you started 

Corgi relies on ~evil-mode~, which Emulates Vim. For basic editing (insert,
delete, copy, paste, etc.) we recommend going through a Vim tutorial.

For other commands like opening files or jumping around windows (panes/splits)
we follow the conventions set out by Spacemacs, where all commands start with
hitting the space bar (~SPC~), typically followed by a prefix key denoting a
category (e.g. ~f~ for "file") and a final key for the specific command. So e.g.
~SPC f f~ to open a file.

Press ~SPC~ or ~SPC f~ and wait a moment to get a list of options.

Besides this ~SPC~ "leader key" we also use ~,~ for mode-specific commands, e.g.
in a Clojure buffer ~, j j~ will "Jack-in" a REPL.

*** General

~SPC SPC~ : execute command (Emacs M-x)

*** Window ~SPC w~

- ~SPC [0...9]~ - go to window number [0..9]
- ~SPC w /~ - split window vertically
- ~SPC w -~ - split window horizontally
- ~SPC w d~ - delete window
- ~SPC w 1~- extend current window to whole screen

*** buffers ~SPC b~

- ~SPC b b~ - list of all buffers
- ~SPC b d~ - kill current buffer (not delete)

*** file ~SPC f~

- ~SPC f s~ - save a file
- ~SPC p p~ - open a project
- ~SPC f f~ - find a file
- ~SPC p f~ - find a file in current project

*** Getting help ~SPC h~

- ~SPC h~ - help system
- ~SPC h d f~ - description of selected function
- ~SPC h d k~ - description of selected key binding

*** Working with REPLs

- ~, s c~ connect to a REPL / process
- ~, s s~ toggle between REPL and code buffer
- ~, s q~ quit current REPL
- ~, s Q~ quit all REPLs for the current project/session
- ~, j j~ connect to a regular REPL (Clojure)
- ~, j o~ connect to "other" REPL (ClojureScript)
- ~, j a~ connect to "all" (Clojure + ClojureScript)
- ~, l l~ link current project/buffer to an open REPL session

*** Structural editing

- ~>~ slurp forward
- ~<~ barf forward
- ~SPC x s~ splice backward
- ~SPC x t~ transpose sexp
- ~L~ forward sexp
- ~H~ backward sexp

The latter two are "text objects" that can be combined with other vim-style
operations

- ~yL~ copy next sexp (paste with ~p~
- ~dL~ delete next sexp
- ~cL~ "change" sexp (delete and switch to insert mode)

* Packages
** corgi-defaults
** corgi-editor
** corgi-emacs-lisp
** corgi-commands
** corgi-clojure
** corgi-stateline
** corkey

* Differences from Vim

Generally we don't override Evil's keybindings, and Evil in turns emulates vim
closely. Some differences

- `L` and `H` move forward/backward by one s-expression, instead of moving to
  the beginning/end of the buffer
- `SPC` and `,` are both used as leader/prefix keys. Press either and wait a bit
  to see what they can do.
